#!/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2020 Christian Göttel

# Convert a PowerSpy log generated by powerspy.py to a CSV file.
# usage: ./powerspy_log2csv.sh <PowerSpy log>

# Debug
#set -x

# Prevent locale nonsense from breaking basic text processing.
LC_ALL=C
export LC_ALL

if [ -x "./error.sh" ]
then
    # Direct invocation
    . ./error.sh
else
    # Indirect invocation through a script in a subdirectory
    . ../error.sh
fi

[ $# -ne 1 ] && fail "main" "usage: $0 <PowerSpy log>"

# The first line in the PowerSpy log contains the header, which is not needed
sed -e '1 d;s/[[:space:]]\+/,/g' "$1" >"${1%log}csv"
